export interface IDoctor {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber: string;
  specialization: DoctorSpecialization;
  doctorType: DoctorType;
  department: Department;
  medicalInstituteId: string;
  createdAt: string;
  updatedAt: string;
}

export enum Department {
  ANESTHESIOLOGY = "ANESTHESIOLOGY",
  CARDIOLOGY = "CARDIOLOGY",
  DERMATOLOGY = "DERMATOLOGY",
  GENERAL = "GENERAL",
  GASTROENTEROLOGY = "GASTROENTEROLOGY",
  NEUROLOGY = "NEUROLOGY",
  OBSTETRICS_GYNECOLOGY = "OBSTETRICS_GYNECOLOGY",
  ONCOLOGY = "ONCOLOGY",
  OPHTHALMOLOGY = "OPHTHALMOLOGY",
  ORTHOPEDICS = "ORTHOPEDICS",
  PEDIATRICS = "PEDIATRICS",
  PSYCHIATRY = "PSYCHIATRY",
  RADIOLOGY = "RADIOLOGY",
  SURGERY = "SURGERY",
  UROLOGY = "UROLOGY"
}

export enum DoctorSpecialization {
  GENERAL_MEDICINE = "GENERAL_MEDICINE",
  INTERNAL_MEDICINE = "INTERNAL_MEDICINE",
  ORTHOPAEDICS = "ORTHOPAEDICS",
  PAEDIATRICS = "PAEDIATRICS",
  CARDIOLOGY = "CARDIOLOGY",
  NEUROLOGY = "NEUROLOGY",
  GASTROENTEROLOGY = "GASTROENTEROLOGY",
  OPHTHALMOLOGY = "OPHTHALMOLOGY",
  ENT = "ENT",
  DERMATOLOGY = "DERMATOLOGY",
  GYNAECOLOGY_OBSTETRICS = "GYNAECOLOGY_OBSTETRICS",
  RADIOLOGY = "RADIOLOGY",
  ANESTHESIOLOGY = "ANESTHESIOLOGY",
  PSYCHIATRY = "PSYCHIATRY",
}

export enum DoctorType {
  INDIVIDUAL = "INDIVIDUAL",
  CORPORATE = "CORPORATE"
}
